[package]
name = "basicsrust"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
serde_json = "1.0.145"
serde = {version = "1.0.145", features = ["derive"] }
borsh = {version="1.5.7",features=["derive"]}

